# Generated by Django 3.1.7 on 2021-05-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_auto_20210526_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
